---
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
trigger:
  - master
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhema'
    repository: 'hema789 / nop'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'hema$(Build.BuildId)'